
apiVersion: v1
kind: Service
metadata:
  name: logstash-emailservice
  namespace: elasticsearch
spec:
  selector:
    app: logstash-emailservice
  ports:
  - protocol: TCP
    port: 5044
    targetPort: 5044
  type: ClusterIP
