
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat
  namespace: elasticsearch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: filebeat-namespace-access
rules:
  - apiGroups: [""]
    resources: ["namespaces", "nodes", "pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: filebeat-namespace-access-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: filebeat-namespace-access
subjects:
  - kind: ServiceAccount
    name: filebeat
    namespace: elasticsearch
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-emailservice
  namespace: elasticsearch
  labels:
    app: filebeat
data:
  filebeat.yml: |
    filebeat.inputs:
      - type: container
        enabled: true
        id: emailservice-filestream
        paths:
          - /var/log/containers/emailservice*.log
        json.keys_under_root: true
        json.add_error_key: true

        #fields_under_root: true
        fields:
          log_source: "emailservice"
        processors:
          #- dissect:
          #    tokenizer: "%{timestamp}|%{level}|%{component}|%{message}"
          #    field: "message"
          #    target_prefix: "parsed"
          - add_kubernetes_metadata:
              in_cluster: true


    output.logstash:
      hosts: ["logstash-emailservice:5044"]
    

    logging.level: info
    monitoring.enabled: false
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat-emailservice
  namespace: elasticsearch
  labels:
    app: filebeat
spec:
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat
    spec:
      serviceAccountName: filebeat
      containers:
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:8.12.0
          args: ["-c", "/usr/share/filebeat/filebeat.yml", "-e"]
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: config
              mountPath: /usr/share/filebeat/filebeat.yml
              subPath: filebeat.yml
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - name: dockersock
              mountPath: /var/run/docker.sock
              readOnly: true
            - name: containers
              mountPath: /var/log/containers
              readOnly: true

      volumes:
        - name: config
          configMap:
            name: filebeat-emailservice
        - name: varlog
          hostPath:
            path: /var/log
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
        - name: containers
          hostPath:
            path: /var/log/containers

