apiVersion: v1
kind: Secret
metadata:
  name: elastic-credentials
  namespace: elasticsearch
type: Opaque
data:
  username: ZWxhc3RpYw==              # base64 for 'elastic'
  password: NTMzU0JqVGE1VW90V0FRNDdGOTIxWTlT # base64 for '533SBjTa5UotWAQ47F921Y9S'
