apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-observability
  namespace: elasticsearch
spec:
  version: 8.12.0
  count: 1
  elasticsearchRef:
    name: elk-stack-observability
  http:
    service:
      spec:
        type: LoadBalancer
      metadata:
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    tls:
      selfSignedCertificate:
        disabled: true
  podTemplate:
    spec:
      containers:
        - name: kibana
          resources:
            limits:
              memory: 2Gi
              cpu: 1